font_size 13.0
de_window_decorations yes
background #1d252c
foreground #b7c5d3
cursor #fefff0

selection_background #28323b
selection_foreground #b7c5d3

color0  #1d252c
color1  #d95468
color2  #8bd49c
color3  #ebbf83
color4  #539afc
color5  #b62d65
color6  #70e1e8
color7  #b7c5d3
color8  #404b53
color9  #d95468
color10 #8bd49c
color11 #ebbf83
color12 #539afc
color13 #b62d65
color14 #70e1e8
color15 #ffffff
